/**
 * The calendar: real Formula 1 circuits, venues and countries.
 *
 * ## Layouts
 *
 * The centreline for every circuit is real data, in `circuitData.js`, generated by
 * `scripts/fetch-circuits.mjs` from published centrelines and -- where none is
 * published -- from the circuit outline's medial axis. See that script for sources
 * and attribution.
 *
 * What is in this file is everything *about* a circuit: name, venue, city,
 * country, corner count, lap character, surface grip, race distance, and the
 * theme the renderer uses for its sky and grass.
 *
 * ## The pin format, retained
 *
 * `circuitShapes.js` still offers `profileFromPins`, which builds a loop from a
 * base radius plus corner pins. Nothing in the game uses it for a real circuit any
 * more -- it is kept because the radial-profile approach is still the only way to
 * generate a *new* closed loop, and its failure modes are documented where it is
 * implemented.
 *
 * Names of circuits, teams and drivers are used nominatively, to identify the
 * real-world subjects this game is a homage to. No team or series asset is
 * included or reproduced.
 */

import { centrelineFor } from './circuitData.js';

/**
 * Rotate a ring of points by `angle` degrees.
 * @param {Array<{x: number, z: number}>} points
 * @param {number} angle degrees
 */
/*
 * Layouts are the real centrelines.
 *
 * Generated by `scripts/fetch-circuits.mjs` from published centreline data and,
 * where none is published, from the circuit outline's medial axis. Each is
 * rescaled so the lap length matches the real one.
 *
 * These were radial profiles until recently -- a base radius plus corner pins,
 * which cannot produce a specific layout because a star-shaped loop has no room
 * for a hairpin next to a long straight. Real centreline data does, so the whole
 * generator was replaced rather than approximated harder.
 */

/**
 * The real centreline for a circuit, in metres.
 *
 * `angle` rotates the loop so the start/finish straight and the grid sit sensibly
 * relative to the corner sequence; rotation is free, shape is not, so this is the
 * only geometric freedom left.
 */
export function circuitLayout(circuit) {
  const points = centrelineFor(circuit.id);
  const rotation = ((circuit.angle ?? 0) * Math.PI) / 180;
  if (!rotation) return points;
  const cos = Math.cos(rotation);
  const sin = Math.sin(rotation);
  return points.map((point) => ({ x: point.x * cos - point.z * sin, z: point.x * sin + point.z * cos }));
}

const RAW = [
  {
    id: 'bahrain',
    name: 'Bahrain International Circuit',
    city: 'Sakhir',
    country: 'Bahrain',
    tag: 'Fast · Braking',
    blurb: 'Long straights into heavy braking, with a tight infield section that catches cars out.',
    venue: 'Sakhir, Bahrain',
    length: 5.412,
    cornerCount: 15,
    theme: { sky: 0xd9b48a, fog: 0xe6c9a4, grass: 0x8a7a4e, kerb: 0xe8437f, daylight: 1.12 },
    scale: 1,
    width: 14,
    laps: 4,
    grip: 1.0,
    angle: -96,
    radius: 708,
    corners: [
      { at: 0, radius: 1.14, spread: 30 },
      { at: 42, radius: 0.81, spread: 20 },
      { at: 66, radius: 0.74, spread: 16 },
      { at: 104, radius: 1.17, spread: 26 },
      { at: 140, radius: 0.77, spread: 15 },
      { at: 168, radius: 0.81, spread: 17 },
      { at: 206, radius: 1.15, spread: 28 },
      { at: 246, radius: 0.84, spread: 19 },
      { at: 292, radius: 1.18, spread: 24 },
      { at: 330, radius: 0.79, spread: 18 }
    ]
  },
  {
    id: 'jeddah',
    name: 'Jeddah Corniche Circuit',
    city: 'Jeddah',
    country: 'Saudi Arabia',
    tag: 'Very Fast · Street',
    blurb: 'A near-flat street circuit where top speed matters more than anything else.',
    venue: 'Jeddah, Saudi Arabia',
    length: 6.174,
    cornerCount: 27,
    theme: { sky: 0xe8c99a, fog: 0xf0d9b4, grass: 0x9a8a5e, kerb: 0x22c55e, daylight: 1.2 },
    scale: 1,
    width: 15,
    laps: 3,
    grip: 0.98,
    angle: -70,
    radius: 789,
    corners: [
      { at: 0, radius: 1.1394, spread: 34 },
      { at: 38, radius: 0.8138, spread: 14 },
      { at: 58, radius: 0.7731, spread: 12 },
      { at: 88, radius: 1.0987, spread: 22 },
      { at: 118, radius: 0.7935, spread: 13 },
      { at: 146, radius: 0.8342, spread: 12 },
      { at: 176, radius: 1.119, spread: 24 },
      { at: 210, radius: 0.8138, spread: 13 },
      { at: 244, radius: 1.1089, spread: 22 },
      { at: 276, radius: 0.8037, spread: 12 },
      { at: 306, radius: 0.8444, spread: 13 },
      { at: 336, radius: 1.1292, spread: 26 }
    ]
  },
  {
    id: 'melbourne',
    name: 'Albert Park Circuit',
    city: 'Melbourne',
    country: 'Australia',
    tag: 'Flowing · Street',
    blurb: 'Fast, flowing parkland speed with a couple of heavy stops that decide the race.',
    venue: 'Melbourne, Australia',
    length: 5.278,
    cornerCount: 14,
    theme: { sky: 0x9fc6e8, fog: 0xbfd8ee, grass: 0x4c8a52, kerb: 0xf472b6, daylight: 0.98 },
    scale: 1,
    width: 13.5,
    laps: 4,
    grip: 1.0,
    angle: -104,
    radius: 734,
    corners: [
      { at: 0, radius: 1.1667, spread: 30 },
      { at: 44, radius: 0.8571, spread: 18 },
      { at: 82, radius: 1.1667, spread: 26 },
      { at: 126, radius: 0.8333, spread: 16 },
      { at: 160, radius: 0.9048, spread: 17 },
      { at: 198, radius: 1.1905, spread: 28 },
      { at: 240, radius: 0.881, spread: 18 },
      { at: 282, radius: 1.1786, spread: 26 },
      { at: 322, radius: 0.869, spread: 17 }
    ]
  },
  {
    /*
     * Sepang. Not on the standard calendar, but the 2026 Bahrain round moved here
     * in October, so it is selectable alongside Bahrain rather than replacing it.
     * Both stay in the game.
     */
    id: 'sepang',
    name: 'Sepang International Circuit',
    city: 'Sepang',
    country: 'Malaysia',
    tag: 'Flowing · Tropical',
    blurb: 'Wide, flowing corners under the heat. Long straights and a technical back section.',
    venue: 'Sepang, Malaysia',
    length: 5.543,
    cornerCount: 15,
    theme: { sky: 0x8ec8e4, fog: 0xb4d8ea, grass: 0x3f7f4e, kerb: 0xdc2626, daylight: 1.08 },
    scale: 1,
    width: 14,
    laps: 4,
    grip: 1.0,
    angle: -104,
    radius: 700
  },
  {
    id: 'suzuka',
    name: 'Suzuka International Racing Course',
    city: 'Suzuka',
    country: 'Japan',
    tag: 'Flowing · Technical',
    blurb: 'A figure-of-eight of long curves and linked esses. Rewards rhythm over bravery.',
    venue: 'Suzuka, Japan',
    length: 5.807,
    cornerCount: 18,
    theme: { sky: 0x8fc7f0, fog: 0xa9d3f2, grass: 0x3f7a4a, kerb: 0xe8437f, daylight: 1.0 },
    scale: 1,
    width: 13.5,
    laps: 4,
    grip: 1.02,
    angle: -96,
    radius: 712,
    corners: [
      { at: 0, radius: 1.1459, spread: 30 },
      { at: 40, radius: 0.8216, spread: 18 },
      { at: 70, radius: 0.7568, spread: 14 },
      { at: 100, radius: 1.1351, spread: 26 },
      { at: 136, radius: 0.7784, spread: 13 },
      { at: 162, radius: 0.7351, spread: 12 },
      { at: 192, radius: 1.1568, spread: 28 },
      { at: 230, radius: 0.8, spread: 16 },
      { at: 262, radius: 0.7568, spread: 13 },
      { at: 296, radius: 1.1459, spread: 26 },
      { at: 330, radius: 0.7892, spread: 15 }
    ]
  },
  {
    id: 'shanghai',
    name: 'Shanghai International Circuit',
    city: 'Shanghai',
    country: 'China',
    tag: 'Fast · Long Straights',
    blurb: 'Longest straights on the calendar feeding a sequence of medium-speed corners.',
    venue: 'Shanghai, China',
    length: 5.451,
    cornerCount: 16,
    theme: { sky: 0xa9bcc9, fog: 0xc2d2dc, grass: 0x4a7a52, kerb: 0xef4444, daylight: 0.9 },
    scale: 1,
    width: 14,
    laps: 4,
    grip: 1.0,
    angle: -88,
    radius: 710,
    corners: [
      { at: 0, radius: 1.1636, spread: 32 },
      { at: 40, radius: 0.841, spread: 17 },
      { at: 68, radius: 0.8065, spread: 15 },
      { at: 100, radius: 1.1866, spread: 28 },
      { at: 138, radius: 0.8295, spread: 15 },
      { at: 168, radius: 0.7949, spread: 13 },
      { at: 200, radius: 1.1751, spread: 28 },
      { at: 242, radius: 0.841, spread: 16 },
      { at: 276, radius: 0.818, spread: 14 },
      { at: 312, radius: 1.1751, spread: 26 }
    ]
  },
  {
    id: 'miami',
    name: 'Miami International Autodrome',
    city: 'Miami Gardens',
    country: 'United States',
    tag: 'Flowing · Street',
    blurb: 'Low grip, open layout and a slow middle section that punishes anyone running wide.',
    venue: 'Miami Gardens, United States',
    length: 5.412,
    cornerCount: 19,
    theme: { sky: 0x7fc4e8, fog: 0xa8d8f0, grass: 0x3d8a5c, kerb: 0x06b6d4, daylight: 1.05 },
    scale: 1,
    width: 15,
    laps: 4,
    grip: 0.9,
    angle: -78,
    radius: 677,
    corners: [
      { at: 0, radius: 1.1717, spread: 30 },
      { at: 42, radius: 0.8121, spread: 16 },
      { at: 76, radius: 0.7657, spread: 13 },
      { at: 112, radius: 1.1601, spread: 26 },
      { at: 148, radius: 0.7889, spread: 14 },
      { at: 182, radius: 0.7541, spread: 12 },
      { at: 216, radius: 1.1833, spread: 28 },
      { at: 252, radius: 0.8121, spread: 15 },
      { at: 288, radius: 0.7773, spread: 13 },
      { at: 324, radius: 1.1601, spread: 26 }
    ]
  },
  {
    id: 'imola',
    name: 'Autodromo Enzo e Dino Ferrari',
    city: 'Imola',
    country: 'Italy',
    tag: 'Flowing · Technical',
    blurb: 'An old-school parkland circuit. Few straights, no room for a mistake, heavy braking.',
    venue: 'Imola, Italy',
    length: 4.909,
    cornerCount: 19,
    theme: { sky: 0xa8c8e0, fog: 0xc0d8ea, grass: 0x5a8a4e, kerb: 0xeab308, daylight: 1.0 },
    scale: 1,
    width: 12.5,
    laps: 5,
    grip: 1.03,
    angle: -118,
    radius: 630,
    corners: [
      { at: 0, radius: 1.1509, spread: 28 },
      { at: 38, radius: 0.844, spread: 15 },
      { at: 70, radius: 0.7928, spread: 13 },
      { at: 104, radius: 1.1637, spread: 26 },
      { at: 140, radius: 0.8184, spread: 13 },
      { at: 172, radius: 0.7801, spread: 12 },
      { at: 206, radius: 1.1765, spread: 27 },
      { at: 244, radius: 0.8312, spread: 14 },
      { at: 278, radius: 0.7928, spread: 13 },
      { at: 314, radius: 1.1509, spread: 26 }
    ]
  },
  {
    id: 'monaco',
    name: 'Circuit de Monaco',
    city: 'Monte Carlo',
    country: 'Monaco',
    tag: 'Slow · Street',
    blurb: 'The shortest lap on the calendar and the least forgiving. Nowhere to hide.',
    venue: 'Monte Carlo, Monaco',
    length: 3.337,
    cornerCount: 19,
    theme: { sky: 0x8ab0d8, fog: 0xa8c8e4, grass: 0x4a7a6a, kerb: 0xef4444, daylight: 1.0 },
    scale: 1,
    width: 11,
    laps: 6,
    grip: 0.95,
    angle: -60,
    radius: 392,
    corners: [
      { at: 0, radius: 1.2053, spread: 26 },
      { at: 34, radius: 0.8098, spread: 14 },
      { at: 62, radius: 0.7533, spread: 12 },
      { at: 96, radius: 1.2429, spread: 24 },
      { at: 132, radius: 0.791, spread: 13 },
      { at: 166, radius: 0.7345, spread: 11 },
      { at: 200, radius: 1.2241, spread: 24 },
      { at: 238, radius: 0.8098, spread: 13 },
      { at: 272, radius: 0.7533, spread: 12 },
      { at: 310, radius: 1.2053, spread: 24 }
    ]
  },
  {
    id: 'montreal',
    name: 'Circuit Gilles Villeneuve',
    city: 'Montreal',
    country: 'Canada',
    tag: 'Flowing · Heavy Braking',
    blurb: 'Walls close in and the back straight is unforgiving. Braking is the whole race.',
    venue: 'Montreal, Canada',
    length: 4.361,
    cornerCount: 14,
    theme: { sky: 0x9cc0dc, fog: 0xbcd4e6, grass: 0x48784e, kerb: 0xdc2626, daylight: 0.98 },
    scale: 1,
    width: 13,
    laps: 5,
    grip: 0.96,
    angle: -92,
    radius: 546,
    corners: [
      { at: 0, radius: 1.1816, spread: 28 },
      { at: 42, radius: 0.8069, spread: 15 },
      { at: 76, radius: 0.7637, spread: 13 },
      { at: 112, radius: 1.196, spread: 26 },
      { at: 152, radius: 0.7925, spread: 14 },
      { at: 188, radius: 0.7493, spread: 12 },
      { at: 226, radius: 1.2104, spread: 28 },
      { at: 268, radius: 0.8069, spread: 15 },
      { at: 310, radius: 0.7781, spread: 13 }
    ]
  },
  {
    id: 'barcelona',
    name: 'Circuit de Barcelona-Catalunya',
    city: 'Montmeló',
    country: 'Spain',
    tag: 'Flowing · Technical',
    blurb: 'Long, committed corners taken at one speed. Very hard on the tyres.',
    venue: 'Montmeló, Spain',
    length: 4.657,
    cornerCount: 14,
    theme: { sky: 0xbcd0e0, fog: 0xd0dfea, grass: 0x5c7a48, kerb: 0xdc2626, daylight: 1.06 },
    scale: 1,
    width: 13,
    laps: 5,
    grip: 1.04,
    angle: -100,
    radius: 601,
    corners: [
      { at: 0, radius: 1.1741, spread: 28 },
      { at: 46, radius: 0.8232, spread: 16 },
      { at: 86, radius: 0.7827, spread: 14 },
      { at: 128, radius: 1.1876, spread: 27 },
      { at: 170, radius: 0.8097, spread: 15 },
      { at: 210, radius: 0.7692, spread: 14 },
      { at: 252, radius: 1.2011, spread: 28 },
      { at: 296, radius: 0.8232, spread: 16 },
      { at: 334, radius: 0.7962, spread: 14 }
    ]
  },
  {
    id: 'spielberg',
    name: 'Red Bull Ring',
    city: 'Spielberg',
    country: 'Austria',
    tag: 'Very Fast · Open',
    blurb: 'Enormous elevation change and almost no slow corners. Top speed is king.',
    venue: 'Spielberg, Austria',
    length: 4.318,
    cornerCount: 10,
    theme: { sky: 0x9cc8e8, fog: 0xbcdcec, grass: 0x54803f, kerb: 0x3b82f6, daylight: 1.0 },
    scale: 1,
    width: 13,
    laps: 5,
    grip: 1.01,
    angle: -108,
    radius: 561,
    corners: [
      { at: 0, radius: 1.2064, spread: 30 },
      { at: 48, radius: 0.8576, spread: 16 },
      { at: 84, radius: 0.814, spread: 13 },
      { at: 124, radius: 1.2209, spread: 28 },
      { at: 172, radius: 0.843, spread: 15 },
      { at: 212, radius: 0.7994, spread: 13 },
      { at: 252, radius: 1.2355, spread: 28 },
      { at: 300, radius: 0.8576, spread: 15 },
      { at: 336, radius: 0.8285, spread: 14 }
    ]
  },
  {
    id: 'silverstone',
    name: 'Silverstone Circuit',
    city: 'Silverstone',
    country: 'United Kingdom',
    tag: 'Very Fast · High Downforce',
    blurb: 'Flat-out from one corner to the next. The benchmark for aerodynamic grip.',
    venue: 'Silverstone, United Kingdom',
    length: 5.891,
    cornerCount: 18,
    theme: { sky: 0xa8bcc8, fog: 0xc4d4de, grass: 0x4e7a4c, kerb: 0x1d4ed8, daylight: 0.94 },
    scale: 1,
    width: 13.5,
    laps: 4,
    grip: 1.06,
    angle: -84,
    radius: 764,
    corners: [
      { at: 0, radius: 1.1514, spread: 32 },
      { at: 42, radius: 0.8316, spread: 17 },
      { at: 74, radius: 0.7889, spread: 15 },
      { at: 108, radius: 1.162, spread: 28 },
      { at: 144, radius: 0.8102, spread: 16 },
      { at: 178, radius: 0.7676, spread: 14 },
      { at: 212, radius: 1.1514, spread: 28 },
      { at: 248, radius: 0.8209, spread: 16 },
      { at: 282, radius: 0.7889, spread: 15 },
      { at: 318, radius: 1.162, spread: 28 }
    ]
  },
  {
    id: 'hungaroring',
    name: 'Hungaroring',
    city: 'Budapest',
    country: 'Hungary',
    tag: 'Flowing · Slow',
    blurb: 'A slow, twisty lap with no straights worth the name. Overtaking is rare.',
    venue: 'Budapest, Hungary',
    length: 4.381,
    cornerCount: 14,
    theme: { sky: 0xc4d0d8, fog: 0xd4dde4, grass: 0x6a8a48, kerb: 0xdc2626, daylight: 1.02 },
    scale: 1,
    width: 12.5,
    laps: 5,
    grip: 1.0,
    angle: -114,
    radius: 575,
    corners: [
      { at: 0, radius: 1.1621, spread: 26 },
      { at: 44, radius: 0.8321, spread: 16 },
      { at: 80, radius: 0.7891, spread: 14 },
      { at: 120, radius: 1.1765, spread: 27 },
      { at: 160, radius: 0.8178, spread: 15 },
      { at: 200, radius: 0.7747, spread: 13 },
      { at: 244, radius: 1.1908, spread: 27 },
      { at: 288, radius: 0.8321, spread: 16 },
      { at: 326, radius: 0.7891, spread: 14 }
    ]
  },
  {
    id: 'spa',
    name: 'Circuit de Spa-Francorchamps',
    city: 'Stavelot',
    country: 'Belgium',
    tag: 'Very Fast · Iconic',
    blurb: 'The longest and fastest lap on the calendar, and the most dramatic.',
    venue: 'Stavelot, Belgium',
    length: 7.004,
    cornerCount: 19,
    theme: { sky: 0x8ea8b8, fog: 0xaac0cc, grass: 0x3f6b45, kerb: 0xef4444, daylight: 0.9 },
    scale: 1,
    width: 13,
    laps: 3,
    grip: 1.05,
    angle: -76,
    radius: 934,
    corners: [
      { at: 0, radius: 1.1659, spread: 36 },
      { at: 44, radius: 0.8251, spread: 20 },
      { at: 82, radius: 0.7713, spread: 18 },
      { at: 124, radius: 1.157, spread: 30 },
      { at: 166, radius: 0.8072, spread: 18 },
      { at: 206, radius: 0.7623, spread: 17 },
      { at: 250, radius: 1.1749, spread: 30 },
      { at: 292, radius: 0.8161, spread: 19 },
      { at: 330, radius: 0.7803, spread: 18 }
    ]
  },
  {
    id: 'zandvoort',
    name: 'Circuit Zandvoort',
    city: 'Zandvoort',
    country: 'Netherlands',
    tag: 'Fast · Banked',
    blurb: 'Sand dunes, a steep banking and a committed final corner taken near the limit.',
    venue: 'Zandvoort, Netherlands',
    length: 4.259,
    cornerCount: 14,
    theme: { sky: 0xa8c4dc, fog: 0xc2d8e8, grass: 0x6a8a52, kerb: 0xef4444, daylight: 0.96 },
    scale: 1,
    width: 13,
    laps: 5,
    grip: 1.0,
    angle: -98,
    radius: 546,
    corners: [
      { at: 0, radius: 1.1799, spread: 28 },
      { at: 46, radius: 0.826, spread: 16 },
      { at: 84, radius: 0.7817, spread: 14 },
      { at: 126, radius: 1.1947, spread: 27 },
      { at: 168, radius: 0.8112, spread: 15 },
      { at: 208, radius: 0.767, spread: 13 },
      { at: 252, radius: 1.2094, spread: 28 },
      { at: 296, radius: 0.826, spread: 16 },
      { at: 334, radius: 0.7965, replace: undefined, spread: 14 }
    ]
  },
  {
    id: 'monza',
    name: 'Autodromo Nazionale Monza',
    city: 'Monza',
    country: 'Italy',
    tag: 'Very Fast · Slipstream',
    blurb: 'Full throttle from the line to the first chicane. Slipstreaming is everything.',
    venue: 'Monza, Italy',
    length: 5.793,
    cornerCount: 11,
    theme: { sky: 0xbcc8d0, fog: 0xd0dae0, grass: 0x5a7a4a, kerb: 0xdc2626, daylight: 1.0 },
    scale: 1,
    width: 13,
    laps: 4,
    grip: 1.02,
    angle: -102,
    radius: 687,
    corners: [
      { at: 0, radius: 1.2134, spread: 40 },
      { at: 46, radius: 0.7801, spread: 14 },
      { at: 70, radius: 0.7367, spread: 12 },
      { at: 112, radius: 1.2026, spread: 34 },
      { at: 162, radius: 0.8017, spread: 14 },
      { at: 196, radius: 0.7476, spread: 12 },
      { at: 240, radius: 1.2243, spread: 36 },
      { at: 292, radius: 0.7909, spread: 14 },
      { at: 330, radius: 0.7584, spread: 13 }
    ]
  },
  {
    id: 'baku',
    name: 'Baku City Circuit',
    city: 'Baku',
    country: 'Azerbaijan',
    tag: 'Very Fast · Street',
    blurb: 'A 2.2km straight along the seafront, then the tightest section on the calendar.',
    venue: 'Baku, Azerbaijan',
    length: 6.003,
    cornerCount: 20,
    theme: { sky: 0x9cb8cc, fog: 0xb8ccd8, grass: 0x5a6b52, kerb: 0x06b6d4, daylight: 1.04 },
    scale: 1,
    width: 14,
    laps: 4,
    grip: 0.94,
    angle: -66,
    radius: 627,
    corners: [
      { at: 0, radius: 1.2029, spread: 38 },
      { at: 42, radius: 0.8159, spread: 13 },
      { at: 62, radius: 0.6695, spread: 10 },
      { at: 88, radius: 1.1715, spread: 26 },
      { at: 124, radius: 0.795, spread: 12 },
      { at: 146, radius: 0.659, spread: 10 },
      { at: 176, radius: 1.1925, spread: 28 },
      { at: 214, radius: 0.8054, spread: 12 },
      { at: 238, radius: 0.6695, spread: 10 },
      { at: 268, radius: 1.182, spread: 26 },
      { at: 306, radius: 0.8159, spread: 13 },
      { at: 332, radius: 0.6904, spread: 11 }
    ]
  },
  {
    id: 'singapore',
    name: 'Marina Bay Street Circuit',
    city: 'Singapore',
    country: 'Singapore',
    tag: 'Slow · Night Street',
    blurb: 'Physically impossible braking distances between walls. Precision over bravery.',
    venue: 'Singapore',
    length: 4.94,
    cornerCount: 19,
    theme: { sky: 0x101828, fog: 0x1c2a3c, grass: 0x2a3a2e, kerb: 0xef4444, daylight: 0.34 },
    scale: 1,
    width: 12.5,
    laps: 5,
    grip: 0.93,
    angle: -72,
    radius: 616,
    corners: [
      { at: 0, radius: 1.145, spread: 26 },
      { at: 40, radius: 0.8142, spread: 14 },
      { at: 70, radius: 0.7634, spread: 12 },
      { at: 104, radius: 1.1578, spread: 25 },
      { at: 140, radius: 0.8015, spread: 13 },
      { at: 172, radius: 0.7506, spread: 11 },
      { at: 206, radius: 1.1705, spread: 26 },
      { at: 244, radius: 0.8142, spread: 14 },
      { at: 278, radius: 0.7634, spread: 12 },
      { at: 314, radius: 1.145, spread: 25 }
    ]
  },
  {
    id: 'austin',
    name: 'Circuit of the Americas',
    city: 'Austin',
    country: 'United States',
    tag: 'Mixed · Esines',
    blurb: 'A blend of long straights and a tight twisty section that catches out over-eager drivers.',
    venue: 'Austin, United States',
    length: 5.513,
    cornerCount: 20,
    theme: { sky: 0xb0c4d4, fog: 0xc8d8e4, grass: 0x4e7a4c, kerb: 0xdc2626, daylight: 1.05 },
    scale: 1,
    width: 14,
    laps: 4,
    grip: 1.0,
    angle: -88,
    radius: 636,
    corners: [
      { at: 0, radius: 1.1731, spread: 30 },
      { at: 40, radius: 0.7973, spread: 15 },
      { at: 68, radius: 0.7062, spread: 11 },
      { at: 96, radius: 1.1617, spread: 26 },
      { at: 130, radius: 0.7859, spread: 13 },
      { at: 158, radius: 0.6948, spread: 11 },
      { at: 188, radius: 1.1731, spread: 26 },
      { at: 224, radius: 0.7973, spread: 14 },
      { at: 254, radius: 0.7062, spread: 11 },
      { at: 284, radius: 1.1617, spread: 26 },
      { at: 318, radius: 0.7859, spread: 13 }
    ]
  },
  {
    id: 'mexico',
    name: 'Autodromo Hermanos Rodriguez',
    city: 'Mexico City',
    country: 'Mexico',
    tag: 'Flowing · Thin Air',
    blurb: 'High altitude means less downforce and more slide than anywhere else.',
    venue: 'Mexico City, Mexico',
    length: 4.304,
    cornerCount: 17,
    theme: { sky: 0xc8b48a, fog: 0xdcca9e, grass: 0x7a8a4a, kerb: 0xea580c, daylight: 1.1 },
    scale: 1,
    width: 12.5,
    laps: 5,
    grip: 0.95,
    angle: -94,
    radius: 522,
    corners: [
      { at: 0, radius: 1.1971, spread: 28 },
      { at: 40, radius: 0.8175, spread: 15 },
      { at: 74, radius: 0.7591, spread: 12 },
      { at: 110, radius: 1.2117, spread: 27 },
      { at: 148, radius: 0.8029, spread: 14 },
      { at: 182, radius: 0.7445, spread: 12 },
      { at: 216, radius: 1.2263, spread: 28 },
      { at: 256, radius: 0.8175, spread: 15 },
      { at: 292, radius: 0.7591, spread: 12 },
      { at: 326, radius: 1.1971, spread: 27 }
    ]
  },
  {
    id: 'interlagos',
    name: 'Autodromo Jose Carlos Pace',
    city: 'Sao Paulo',
    country: 'Brazil',
    tag: 'Flowing · Anti-Clockwise',
    blurb: 'A banked run to the line and a sequence of downhill esses that punishes the brave.',
    venue: 'Sao Paulo, Brazil',
    length: 4.309,
    cornerCount: 15,
    theme: { sky: 0xb4c8a8, fog: 0xccdcc0, grass: 0x46803e, kerb: 0xfacc15, daylight: 1.0 },
    scale: 1,
    width: 13,
    laps: 5,
    grip: 1.01,
    angle: -112,
    radius: 513,
    corners: [
      { at: 0, radius: 1.2099, spread: 28 },
      { at: 42, radius: 0.8163, spread: 15 },
      { at: 76, radius: 0.7434, spread: 12 },
      { at: 112, radius: 1.2245, spread: 27 },
      { at: 150, radius: 0.8017, spread: 14 },
      { at: 184, radius: 0.7289, spread: 12 },
      { at: 220, radius: 1.2391, spread: 28 },
      { at: 260, radius: 0.8163, spread: 15 },
      { at: 298, radius: 0.758, spread: 12 },
      { at: 332, radius: 1.2099, spread: 27 }
    ]
  },
  {
    id: 'vegas',
    name: 'Las Vegas Strip Circuit',
    city: 'Las Vegas',
    country: 'United States',
    tag: 'Very Fast · Night Street',
    blurb: 'Enormous speed down a Strip that was a road this morning. Nerve, not finesse.',
    venue: 'Las Vegas, United States',
    length: 6.201,
    cornerCount: 17,
    theme: { sky: 0x0d1220, fog: 0x1a2138, grass: 0x22303a, kerb: 0xf0abfc, daylight: 0.3 },
    scale: 1,
    width: 15,
    laps: 3,
    grip: 0.97,
    angle: -80,
    radius: 696,
    corners: [
      { at: 0, radius: 1.2449, spread: 40 },
      { at: 48, radius: 0.83, spread: 14 },
      { at: 74, radius: 0.7085, spread: 11 },
      { at: 108, radius: 1.2247, spread: 28 },
      { at: 152, radius: 0.8198, spread: 13 },
      { at: 180, radius: 0.6984, spread: 11 },
      { at: 214, radius: 1.2348, spread: 28 },
      { at: 258, radius: 0.83, spread: 14 },
      { at: 286, radius: 0.7085, spread: 11 },
      { at: 322, radius: 1.2247, spread: 28 }
    ]
  },
  {
    id: 'yasmarina',
    name: 'Yas Marina Circuit',
    city: 'Abu Dhabi',
    country: 'United Arab Emirates',
    tag: 'Fast · Twilight',
    blurb: 'The season finale under the lights. Long straights into a twisty final sector.',
    venue: 'Abu Dhabi, United Arab Emirates',
    length: 5.281,
    cornerCount: 16,
    theme: { sky: 0x3a4a6a, fog: 0x50608a, grass: 0x36504a, kerb: 0x38bdf8, daylight: 0.5 },
    scale: 1,
    width: 14,
    laps: 4,
    grip: 1.02,
    angle: -96,
    radius: 676,
    corners: [
      { at: 0, radius: 1.1772, spread: 32 },
      { at: 44, radius: 0.8561, spread: 16 },
      { at: 76, radius: 0.7848, spread: 13 },
      { at: 112, radius: 1.1891, spread: 27 },
      { at: 150, radius: 0.8323, spread: 15 },
      { at: 184, radius: 0.7729, spread: 13 },
      { at: 218, radius: 1.201, spread: 28 },
      { at: 256, radius: 0.8561, spread: 16 },
      { at: 292, radius: 0.7848, spread: 13 },
      { at: 326, radius: 1.1772, spread: 26 }
    ]
  }
];

/** Every circuit, with its generated control points attached. */
export const CIRCUITS = RAW.map((circuit) => ({
  ...circuit,
  scale: circuit.scale ?? 1,
  controlPoints: circuitLayout(circuit)
}));

const BY_ID = new Map(CIRCUITS.map((circuit) => [circuit.id, circuit]));

/**
 * Look up a circuit by id.
 * @param {string} id
 */
export function getCircuit(id) {
  const circuit = BY_ID.get(id);
  if (!circuit) throw new Error(`Unknown circuit "${id}"`);
  return circuit;
}

/** All team names, for the entry list. */
export function circuitIds() {
  return CIRCUITS.map((circuit) => circuit.id);
}