/**
 * Per-circuit identity.
 *
 * The centrelines are real, so the shape of each circuit is right. Everything *around*
 * it was generic: the same green, the same stands at the same spacing, the same run-off
 * everywhere. Two circuits that differ by a factor of three in width and are separated
 * by six thousand kilometres looked identical.
 *
 * This is the part that can be got right without visiting the circuits: what kind of
 * place each one is. A street circuit has buildings and walls pressed right up against
 * the barrier and almost no run-off. A parkland circuit has mature trees and houses set
 * back. A permanent circuit in the desert has none of either and a great deal of dust.
 *
 * ## Honesty about the data here
 *
 * Everything in this file is a **setting**, not a survey: what the circuit's surroundings
 * are, at the level of "street / parkland / permanent / desert" and what grows there.
 * That is a claim about the character of a place, and it is a claim that can be made
 * correctly from knowledge of the circuits.
 *
 * It is explicitly *not*:
 *
 * - **Elevation.** Spa's Raidillon and Monaco's climbs are the single most recognisable
 *   thing about both circuits, and neither is modelled. The centres are all at y = 0.
 *   Real elevation needs real survey data -- OSM `ele` tags per node, or a DEM -- and
 *   inventing plausible-looking numbers would be worse than leaving it flat, because a
 *   wrong hill changes the driving as well as the view.
 * - **Corner-by-corner furniture.** Real circuits put gravel traps, kerbs and
 *   barriers in specific places because of specific terrain. The layouts here are
 *   generated by character, not surveyed.
 *
 * Both are listed in the README as known limitations for exactly this reason.
 */

/** How the circuit sits in its surroundings. */
export const SETTING = {
  /** Buildings and walls tight against the barrier. Monaco, Jeddah, Singapore. */
  street: 'street',
  /** Trees and parkland. Melbourne, Montreal. */
  parkland: 'parkland',
  /** Purpose-built venue in open country. Most of the calendar. */
  permanent: 'permanent',
  /** Purpose-built in arid country. Bahrain, Yas Marina. */
  desert: 'desert',
  /** Coastal, with the sea on one side. Miami. */
  coastal: 'coastal'
};

/**
 * Per-circuit surroundings.
 *
 * `treeDensity` and `buildingDensity` are relative, not counts: the renderer places
 * things along the track and needs to know whether this circuit is leafy or bare, not
 * how many individual trees a real circuit has.
 */
const PROFILES = {
  bahrain: { setting: SETTING.desert, treeDensity: 0.1, buildingDensity: 0.05, groundTint: 0xbfae86, dust: 0.7 },
  jeddah: { setting: SETTING.street, treeDensity: 0.15, buildingDensity: 0.85, groundTint: 0xb9ae94, dust: 0.5 },
  melbourne: { setting: SETTING.parkland, treeDensity: 0.85, buildingDensity: 0.4, groundTint: 0x6f8f5a, dust: 0 },
  sepang: { setting: SETTING.permanent, treeDensity: 0.7, buildingDensity: 0.15, groundTint: 0x5f8447, dust: 0 },
  suzuka: { setting: SETTING.permanent, treeDensity: 0.8, buildingDensity: 0.1, groundTint: 0x5d8248, dust: 0 },
  shanghai: { setting: SETTING.permanent, treeDensity: 0.35, buildingDensity: 0.15, groundTint: 0x7d9163, dust: 0 },
  miami: { setting: SETTING.coastal, treeDensity: 0.55, buildingDensity: 0.5, groundTint: 0x8aa06a, dust: 0 },
  imola: { setting: SETTING.permanent, treeDensity: 0.75, buildingDensity: 0.12, groundTint: 0x688a4c, dust: 0 },
  monaco: { setting: SETTING.street, treeDensity: 0.25, buildingDensity: 0.95, groundTint: 0x8f9478, dust: 0 },
  montreal: { setting: SETTING.parkland, treeDensity: 0.8, buildingDensity: 0.25, groundTint: 0x6d8f57, dust: 0 },
  barcelona: { setting: SETTING.permanent, treeDensity: 0.35, buildingDensity: 0.1, groundTint: 0x87a05e, dust: 0.1 },
  spielberg: { setting: SETTING.permanent, treeDensity: 0.6, buildingDensity: 0.08, groundTint: 0x7d9459, dust: 0.1 },
  silverstone: { setting: SETTING.permanent, treeDensity: 0.5, buildingDensity: 0.12, groundTint: 0x7b9463, dust: 0 },
  hungaroring: { setting: SETTING.permanent, treeDensity: 0.45, buildingDensity: 0.1, groundTint: 0x8a9c60, dust: 0.15 },
  spa: { setting: SETTING.permanent, treeDensity: 0.95, buildingDensity: 0.06, groundTint: 0x517a41, dust: 0 },
  zandvoort: { setting: SETTING.parkland, treeDensity: 0.7, buildingDensity: 0.3, groundTint: 0x76935a, dust: 0 },
  monza: { setting: SETTING.parkland, treeDensity: 0.8, buildingDensity: 0.18, groundTint: 0x6d8c50, dust: 0 },
  baku: { setting: SETTING.street, treeDensity: 0.12, buildingDensity: 0.9, groundTint: 0xa89a80, dust: 0.55 },
  singapore: { setting: SETTING.street, treeDensity: 0.5, buildingDensity: 0.92, groundTint: 0x6f9152, dust: 0 },
  austin: { setting: SETTING.permanent, treeDensity: 0.55, buildingDensity: 0.12, groundTint: 0x8a9862, dust: 0.3 },
  mexico: { setting: SETTING.permanent, treeDensity: 0.4, buildingDensity: 0.2, groundTint: 0x84935c, dust: 0.2 },
  interlagos: { setting: SETTING.parkland, treeDensity: 0.85, buildingDensity: 0.12, groundTint: 0x5e8443, dust: 0 },
  vegas: { setting: SETTING.desert, treeDensity: 0.05, buildingDensity: 0.35, groundTint: 0xa89878, dust: 0.6 },
  yasmarina: { setting: SETTING.desert, treeDensity: 0.12, buildingDensity: 0.3, groundTint: 0xb5a481, dust: 0.65 }
};

/**
 * The profile for a circuit, with a safe default.
 *
 * Defaults matter: a circuit with no profile must still build a world, and it must build
 * a *generic* one rather than a broken one.
 *
 * @param {string} id
 */
export function environmentFor(id) {
  return (
    PROFILES[id] ?? {
      setting: SETTING.permanent,
      treeDensity: 0.5,
      buildingDensity: 0.15,
      groundTint: 0x74925a,
      dust: 0.1
    }
  );
}

/**
 * Does this setting put buildings hard against the track?
 *
 * A street circuit is not a permanent circuit with more scenery: the barrier is at the
 * edge of the road, there is effectively no run-off, and the buildings start
 * immediately behind it. That is the single biggest difference in how a circuit *feels*
 * to drive, and it should come from the data rather than from a hand-tuned constant per
 * circuit.
 *
 * @param {string} setting
 */
export function isStreet(setting) {
  return setting === SETTING.street;
}